In [1]:
import os, pathlib
import pandas as pd

df = pd.read_csv("./CEAS_08.csv")
# df.head()



# Take a subset of the dataset (20% of each label)
df_label_0 = df[df['label'] == 0].sample(frac=0.001, random_state=42)
df_label_1 = df[df['label'] == 1].sample(frac=0.001, random_state=42)

df = pd.concat([df_label_0, df_label_1]).sample(frac=1, random_state=42).reset_index(drop=True)

print(f"New dataset size: {len(df)}")
print("Distribution of labels in the subset:")
print(df['label'].value_counts())

New dataset size: 39
Distribution of labels in the subset:
label
1    22
0    17
Name: count, dtype: int64

Imports & Setup

In [3]:
from __future__ import annotations
import os

# Quieter TensorFlow logs: 0=all, 1=INFO off, 2=WARNING off, 3=ERROR only
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import gc
import math
import random
from dataclasses import dataclass
from typing import List, Tuple, Optional

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset as TorchDataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    set_seed,
)

# TextAttack imports
from textattack.models.wrappers import HuggingFaceModelWrapper
from textattack.attack_recipes import TextFoolerJin2019
from textattack import Attacker
from textattack.datasets import Dataset as TADataset

2025-08-28 13:48:56.250645: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756367336.265983 1425607 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756367336.271185 1425607 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1756367336.285437 1425607 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756367336.285460 1425607 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756367336.285462 1425607 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756367336.285463 1425607 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/nazmul/anaconda3/envs/nlp_game/lib/python3.12/site-packages/jieba/_compat.py:18: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

GPU Sanity Check

In [4]:
print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Device count:", torch.cuda.device_count())
if torch.cuda.is_available():
    print("Device name:", torch.cuda.get_device_name(0))

Torch version: 2.8.0+cu128
CUDA available: True
Device count: 1
Device name: NVIDIA GeForce RTX 4060 Ti

Dataset Utilities

In [5]:
@dataclass
class EncodedBatch:
    input_ids: torch.Tensor
    attention_mask: torch.Tensor
    labels: torch.Tensor


class TextClassificationDataset(TorchDataset):
    def __init__(self, texts: List[str], labels: List[int], tokenizer, max_length: int = 256):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = int(self.labels[idx])
        enc = self.tokenizer(
            text,
            truncation=True,
            padding=False,
            max_length=self.max_length,
            return_tensors="pt",
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(label, dtype=torch.long)
        return item

metrics

In [6]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds, average="weighted"),
    }

albert-based classifier

In [7]:
def train_discriminator(
    df: pd.DataFrame,
    save_dir: str = "./albert_phishing_model",
    model_name: str = "albert-base-v2",
    test_size: float = 0.2,
    max_length: int = 256,
    train_batch_size: int = 16,
    eval_batch_size: int = 32,
    learning_rate: float = 5e-5,
    num_train_epochs: int = 3,
    gradient_accumulation_steps: int = 1,
    fp16: bool = True,
    weight_decay: float = 0.01,
    logging_steps: int = 50,
    seed: int = 42,
    from_checkpoint: bool = False,
):
    """Train or resume a PyTorch ALBERT classifier with HuggingFace Trainer.

    Returns: (model, tokenizer, trainer)
    """
    assert {"body", "label"}.issubset(df.columns), "DataFrame must have 'body' and 'label' columns."

    os.makedirs(save_dir, exist_ok=True)
    set_seed(seed)

    # Split
    X_train, X_val, y_train, y_val = train_test_split(
        df["body"].astype(str).tolist(), df["label"].astype(int).tolist(), test_size=test_size, random_state=seed
    )

    # Load tokenizer & model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    if from_checkpoint and os.path.isdir(save_dir) and len(os.listdir(save_dir)) > 0:
        model = AutoModelForSequenceClassification.from_pretrained(save_dir)
    else:
        # Infer number of labels from data
        num_labels = int(pd.Series(y_train + y_val).nunique())
        model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

    # Datasets
    train_ds = TextClassificationDataset(X_train, y_train, tokenizer, max_length)
    val_ds = TextClassificationDataset(X_val, y_val, tokenizer, max_length)

    # Training args
    args = TrainingArguments(
        output_dir=save_dir,
        per_device_train_batch_size=train_batch_size,
        per_device_eval_batch_size=eval_batch_size,
        learning_rate=learning_rate,
        num_train_epochs=num_train_epochs,
        gradient_accumulation_steps=gradient_accumulation_steps,
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        fp16=fp16,
        weight_decay=weight_decay,
        logging_steps=logging_steps,
        report_to=[],  # disable wandb etc.
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    # Save best model + tokenizer
    trainer.save_model(save_dir)
    tokenizer.save_pretrained(save_dir)

    # Cleanup
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return model, tokenizer, trainer

adversarial sample generation (TextAttack)

In [8]:
def generate_adversarial_samples(
    model: torch.nn.Module,
    tokenizer,
    dataset_df: pd.DataFrame,
    max_length: int = 256,
    recipe: str = "textfooler",
    seed: int = 42,
) -> pd.DataFrame:
    """Generate adversarial samples using TextAttack (untargeted misclassification).

    Returns a DataFrame with columns ['body','label'] using the original labels.
    """
    assert {"body", "label"}.issubset(dataset_df.columns)

    set_seed(seed)

    # Prepare TextAttack dataset (list of (text, label))
    tuples: List[Tuple[str, int]] = [
        (str(row["body"]), int(row["label"])) for _, row in dataset_df.iterrows()
    ]

    ta_dataset = TADataset(tuples)

    # Wrap model for TextAttack
    model.eval()
    if torch.cuda.is_available():
        model.to("cuda")
    wrapper = HuggingFaceModelWrapper(model, tokenizer)

    # Select recipe
    if recipe.lower() == "textfooler":
        attack = TextFoolerJin2019.build(wrapper)
    else:
        raise ValueError(f"Unsupported recipe: {recipe}")

    attacker = Attacker(attack, ta_dataset)

    adv_rows = []
    for result in attacker.attack_dataset():
        if getattr(result, "perturbed_result", None) is not None:
            adv_text = result.perturbed_result.attacked_text.text
            original_label = int(result.original_result.ground_truth_output)
            adv_rows.append({"body": adv_text, "label": original_label})

    adv_df = pd.DataFrame(adv_rows, columns=["body", "label"]).dropna()
    return adv_df

multi-round adversarial training game

In [9]:
def adversarial_training_game(
    df: pd.DataFrame,
    rounds: int = 5,
    save_dir: str = "./albert_game_model",
    model_name: str = "albert-base-v2",
    max_length: int = 256,
    train_batch_size: int = 16,
    eval_batch_size: int = 32,
    learning_rate: float = 5e-5,
    num_train_epochs: int = 3,
    gradient_accumulation_steps: int = 1,
    fp16: bool = True,
    weight_decay: float = 0.01,
    logging_steps: int = 50,
    seed: int = 42,
):
    """Run multi-round adversarial training using TextFooler.

    At each round:
      1) Train/update classifier
      2) Generate adversarial examples against the current model (on ALL data)
      3) Augment dataset and dedupe
      4) Save adversarial set for that round

    Returns: (final_model, final_tokenizer, final_df)
    """
    assert {"body", "label"}.issubset(df.columns)
    df = df.copy()
    os.makedirs(save_dir, exist_ok=True)

    for r in range(1, rounds + 1):
        print(f"\n===== Round {r} / {rounds} =====")

        # 1) Train or resume
        model, tokenizer, _ = train_discriminator(
            df=df,
            save_dir=save_dir,
            model_name=model_name,
            test_size=0.2,
            max_length=max_length,
            train_batch_size=train_batch_size,
            eval_batch_size=eval_batch_size,
            learning_rate=learning_rate,
            num_train_epochs=num_train_epochs,
            gradient_accumulation_steps=gradient_accumulation_steps,
            fp16=fp16,
            weight_decay=weight_decay,
            logging_steps=logging_steps,
            seed=seed,
            from_checkpoint=(r > 1),
        )

        # 2) Generate adversarials on the entire dataset
        adv_df = generate_adversarial_samples(
            model=model,
            tokenizer=tokenizer,
            dataset_df=df,
            max_length=max_length,
            recipe="textfooler",
            seed=seed,
        )
        print(f"Generated {len(adv_df)} adversarial samples.")

        # 3) Merge & dedupe
        if not adv_df.empty:
            before = len(df)
            df = pd.concat([df, adv_df], ignore_index=True)
            df.drop_duplicates(subset=["body"], inplace=True)
            after = len(df)
            print(f"Dataset size: {before} -> {after} (after merging adversarials)")
        else:
            print("No adversarial samples generated this round.")

        # 4) Save the adversarial set for this round
        adv_path = os.path.join(save_dir, f"adversarial_round_{r}.csv")
        adv_df.to_csv(adv_path, index=False)
        print(f"Saved adversarial samples to {adv_path}")

        # Cleanup GPU memory between rounds
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return model, tokenizer, df

In [10]:
import nltk
nltk.download("averaged_perceptron_tagger_eng")
nltk.download("wordnet")   # also needed for synonyms
nltk.download("omw-1.4")   # WordNet dependencies

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/nazmul/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /home/nazmul/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/nazmul/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [ ]:
final_model, final_tokenizer, final_dataset = adversarial_training_game(
        df,
        rounds=3,
        save_dir="./albert_game_model",
        model_name="albert-base-v2",
        max_length=256,
        train_batch_size=8,
        eval_batch_size=32,
        learning_rate=5e-5,
        num_train_epochs=3,
        gradient_accumulation_steps=1,
        fp16=True,
        weight_decay=0.01,
        logging_steps=50,
        seed=42,
)

===== Round 1 / 3 =====

Some weights of AlbertForSequenceClassification were not initialized from the model checkpoint at albert-base-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipykernel_1425607/3098119841.py:64: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

textattack: Unknown if model of class <class 'transformers.models.albert.modeling_albert.AlbertForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.

Attack(
  (search_method): GreedyWordSwapWIR(
    (wir_method):  delete
  )
  (goal_function):  UntargetedClassification
  (transformation):  WordSwapEmbedding(
    (max_candidates):  50
    (embedding):  WordEmbedding
  )
  (constraints):
    (0): WordEmbeddingDistance(
        (embedding):  WordEmbedding
        (min_cos_sim):  0.5
        (cased):  False
        (include_unknown_words):  True
        (compare_against_original):  True
      )
    (1): PartOfSpeech(
        (tagger_type):  nltk
        (tagset):  universal
        (allow_verb_noun_swap):  True
        (compare_against_original):  True
      )
    (2): UniversalSentenceEncoder(
        (metric):  angular
        (threshold):  0.840845057
        (window_size):  15
        (skip_text_shorter_than_window):  True
        (compare_against_original):  False
      )
    (3): RepeatModification
    (4): StopwordModification
    (5): InputColumnModification(
        (matching_column_labels):  ['premise', 'hypothesis']
        (columns_to_ignore):  {'premise'}
      )
  (is_black_box):  True
)

  0%|          | 0/10 [00:00<?, ?it/s]I0000 00:00:1756367349.640574 1425607 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 12262 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Ti, pci bus id: 0000:07:00.0, compute capability: 8.9
[Succeeded / Failed / Skipped / Total] 0 / 1 / 0 / 1:  10%|█         | 1/10 [00:12<01:51, 12.42s/it]

--------------------------------------------- Result 1 ---------------------------------------------
[[1 (86%)]] --> [[[FAILED]]]


Dear c202f8eb239faf8d4b0a5c6a41cde453

Summer is a great time to take a week off at work and think about your health & personal life.

And we are glad to aid you with it.

 From now on till 1st of September you can use our specific offer.

Visit our site for more details.

answerdry.com

6 Aug 2008 11:17:23

[Succeeded / Failed / Skipped / Total] 0 / 2 / 0 / 2:  20%|██        | 2/10 [00:16<01:06,  8.32s/it]

--------------------------------------------- Result 2 ---------------------------------------------
[[1 (83%)]] --> [[[FAILED]]]


Why pay more? Get qualitative replica watches here

Replica watches, pens, bags and more... Cheap luxury gifts ...

Ladies and Gents watches from only 9.99 inc. delivery ...

http://dryadsnedsjaw.com/

[Succeeded / Failed / Skipped / Total] 1 / 2 / 0 / 3:  30%|███       | 3/10 [00:20<00:48,  6.95s/it]

--------------------------------------------- Result 3 ---------------------------------------------
[[0 (57%)]] --> [[1 (50%)]]

Hi [[Justin]],

I might [[be]] [[biased]] (x31), but in my experience the [[wast]] majority of [[mac]]
[[laptops]] [[have]] a hardware [[issue]]. In my experience maybe one out of ten mac
laptop [[users]] does _not_ tell about a hardware problem "that [[happened]]
only to my machine, otherwise all mac [[laptops]] are great" ([[tm]]). A
passionate mac user told me once: you buy mac laptops  not because of
but despite the hardware.
And then some stories about the warranty service...
But of course, design and functionality wise they look [[really]] tempting ;-)

jm2c,

  Joerg




Hi [[Timberlake]],

I might [[exists]] [[skewed]] (x31), but in my experience the [[wearied]] majority of [[procurer]]
[[notebook]] [[am]] a hardware [[issuing]]. In my experience maybe one out of ten mac
laptop [[user]] does _not_ tell about a hardware problem "that [[arisen]]
only to my machine, otherwise all mac [[mobile]] are great" ([[trademark]]). A
passionate mac user told me once: you buy mac laptops  not because of
but despite the hardware.
And then some stories about the warranty service...
But of course, design and functionality wise they look [[very]] tempting ;-)

jm2c,

  Joerg

[Succeeded / Failed / Skipped / Total] 2 / 2 / 0 / 4:  40%|████      | 4/10 [00:24<00:36,  6.07s/it]

--------------------------------------------- Result 4 ---------------------------------------------
[[0 (57%)]] --> [[1 (53%)]]

*************************************************************************
                         Call for papers:

                  Dynamics of Knowledge and Belief

                        Workshop at KI-2007,
   30th Annual German Conference on Artificial Intelligence,
                         September 10, 2007
              [[http]]://www.fernuni-hagen.de/wbs/dynamics07

*************************************************************************

Knowledge Representation is one of the major topics in AI. Its concerns
are (logical) formalisms and reasoning, with the intention to explore and
model the basics of intelligent behaviour. In recent years, intelligent
agents in the contexts of open environments and multi agent systems have
become the leading paradigm of the field. Consequently, modern KR methods
have to deal not only with static scenarios, but also with dynamic
modifications in knowledge and belief, due to uncertain or incomplete
information, or to changes in the environment. Moreover, agents are often
expected to learn from past experiences, or to  interact with other
agents, making use of their knowledge and adjusting their beliefs during
argumentation.

The focus of this workshop is on dynamic processes concerning any changes
that an agent's state of knowledge and belief may undergo. Modelling the
continuous cycle of acquiring and applying  knowledge is of particular
interest, so work on relating learning and knowledge representation will
be considered particularly useful. Moreover, the effects of belief changes
on the agent's decisions and behaviour is also within the scope of the
workshop.

We welcome papers on the following and any related topics:
     * Belief revision and belief update
     * Nonmonotonic reasoning
     * Learning and knowledge discovery in data
     * Argumentation theories
     * Decision theory and preferences
     * Action and change

Important Dates:
----------------
     Deadline for Submission:    June 6, 2007
     Notification of Authors:    July 16, 2007
     Final Versions of Papers:   July 30, 2007
     Workshop:                   September 10, 2007

Workshop Organizers and Co-Chairs:
----------------------------------
     Gabriele Kern-Isberner, Universität Dortmund
     Christoph Beierle, FernUniversität in Hagen

Program Committee:
------------------
     Gerd Brewka         Universität Leipzig
     James P. Delgrande  Simon Fraser University
     Jürgen Dix          TU Clausthal-Zellerfeld
     Didier Dubois       Universite Paul Sabatier, Toulouse
     Thomas Eiter        TU Wien
     Esra Erdem          Sabanci University, Istanbul
     Christopher Habel   Universität Hamburg
     Andreas Herzig      Universite Paul Sabatier, Toulouse
     Anthony Hunter      University College London
     Manfred Jaeger      Aalborg University
     Gerhard Lakemeyer   RWTH Aachen
     Jerome Lang         Universite Paul Sabatier, Toulouse
     Bernhard Nebel      Albert-Ludwigs-Universität Freiburg
     Torsten Schaub      Universität Potsdam
     Guillermo Simari    Universidad Nacional del Sur, Bahia Blanca
     Gerhard Weiss       Software Competence Center Hagenberg

Paper Submission and Publication:
---------------------------------
Paper format and submission details are available at
     http://www.fernuni-hagen.de/wbs/dynamics07

**************************************************************************


*************************************************************************
                         Call for papers:

                  Dynamics of Knowledge and Belief

                        Workshop at KI-2007,
   30th Annual German Conference on Artificial Intelligence,
                         September 10, 2007
              [[www]]://www.fernuni-hagen.de/wbs/dynamics07

*************************************************************************

Knowledge Representation is one of the major topics in AI. Its concerns
are (logical) formalisms and reasoning, with the intention to explore and
model the basics of intelligent behaviour. In recent years, intelligent
agents in the contexts of open environments and multi agent systems have
become the leading paradigm of the field. Consequently, modern KR methods
have to deal not only with static scenarios, but also with dynamic
modifications in knowledge and belief, due to uncertain or incomplete
information, or to changes in the environment. Moreover, agents are often
expected to learn from past experiences, or to  interact with other
agents, making use of their knowledge and adjusting their beliefs during
argumentation.

The focus of this workshop is on dynamic processes concerning any changes
that an agent's state of knowledge and belief may undergo. Modelling the
continuous cycle of acquiring and applying  knowledge is of particular
interest, so work on relating learning and knowledge representation will
be considered particularly useful. Moreover, the effects of belief changes
on the agent's decisions and behaviour is also within the scope of the
workshop.

We welcome papers on the following and any related topics:
     * Belief revision and belief update
     * Nonmonotonic reasoning
     * Learning and knowledge discovery in data
     * Argumentation theories
     * Decision theory and preferences
     * Action and change

Important Dates:
----------------
     Deadline for Submission:    June 6, 2007
     Notification of Authors:    July 16, 2007
     Final Versions of Papers:   July 30, 2007
     Workshop:                   September 10, 2007

Workshop Organizers and Co-Chairs:
----------------------------------
     Gabriele Kern-Isberner, Universität Dortmund
     Christoph Beierle, FernUniversität in Hagen

Program Committee:
------------------
     Gerd Brewka         Universität Leipzig
     James P. Delgrande  Simon Fraser University
     Jürgen Dix          TU Clausthal-Zellerfeld
     Didier Dubois       Universite Paul Sabatier, Toulouse
     Thomas Eiter        TU Wien
     Esra Erdem          Sabanci University, Istanbul
     Christopher Habel   Universität Hamburg
     Andreas Herzig      Universite Paul Sabatier, Toulouse
     Anthony Hunter      University College London
     Manfred Jaeger      Aalborg University
     Gerhard Lakemeyer   RWTH Aachen
     Jerome Lang         Universite Paul Sabatier, Toulouse
     Bernhard Nebel      Albert-Ludwigs-Universität Freiburg
     Torsten Schaub      Universität Potsdam
     Guillermo Simari    Universidad Nacional del Sur, Bahia Blanca
     Gerhard Weiss       Software Competence Center Hagenberg

Paper Submission and Publication:
---------------------------------
Paper format and submission details are available at
     http://www.fernuni-hagen.de/wbs/dynamics07

**************************************************************************

[Succeeded / Failed / Skipped / Total] 2 / 3 / 0 / 5:  50%|█████     | 5/10 [00:25<00:25,  5.05s/it]

--------------------------------------------- Result 5 ---------------------------------------------
[[1 (75%)]] --> [[[FAILED]]]

Sharon Stone XXX movie! dowload!
http://www.globalnethost.com.br/movz/mov.php

[Succeeded / Failed / Skipped / Total] 2 / 4 / 1 / 7:  70%|███████   | 7/10 [00:38<00:16,  5.52s/it]

--------------------------------------------- Result 6 ---------------------------------------------
[[1 (76%)]] --> [[[FAILED]]]








  Just some helpful information .
 Small size is one of  the  common problems for many men. However, this problem could be solved in a  safe and inexpensive way. Our Pills Will Expand, Lengthen and Enlarge Your ... !
 We understand  that most  customers need confidentiality and respect every need of our clients. Secure online ordering process, discreet packing, security of your private information are guaranteed.
Order  VPXL today ! - Click Here!







--------------------------------------------- Result 7 ---------------------------------------------
[[1 (51%)]] --> [[[SKIPPED]]]

Bugs item #1387699, was opened at 2005-12-21 21:14
Message generated for change (Comment added) made by david_abrahams
You can respond by visiting:
https://sourceforge.net/tracker/?func=detail&atid=498103&aid=1387699&group_id=61702

Please note that this message will contain a full copy of the comment thread,
including the initial issue submission, for this request,
not just the latest update.
Category: hammie
Group: 1.0.4
Status: Closed
Resolution: Fixed
Priority: 5
Private: No
Submitted By: aikiaboy (aikiaboy)
Assigned to: Nobody/Anonymous (nobody)
Summary: train_on_filter=True needs the db to be opened read/write

Initial Comment:
train_on_filter=True needs the db to be opened
read/write for classification

eg.

========================


[globals]
dbm_type=db3hash
verbose=True
[Headers]
include_score=True
[html_ui]
display_adv_find=True
[Storage]
persistent_use_database=dbm
persistent_storage_file=./hammie.db
[Hammie]
train_on_filter=True

=========================

$ sb_filter.py
asdf
fdsa
Loading state
from /u/k/a/kantor/.spambayes/./hammie.db database
/u/k/a/kantor/.spambayes/./hammie.db is an existing
database, with 2273 spam and 711 ham
Traceback (most recent call last):
  File "/u/k/a/kantor/bin/sb_filter.py", line 257, in ?
    main()
  File "/u/k/a/kantor/bin/sb_filter.py", line 248, in
main
    action(msg)
  File "/u/k/a/kantor/bin/sb_filter.py", line 180, in
filter
    return self.h.filter(msg)
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/hammie.py", line 120, in filter
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/hammie.py", line 162, in train
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/classifier.py", line 273, in learn
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/classifier.py", line 384, in
_add_msg
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/storage.py", line 304, in
_wordinfoset
  File "/s/python-
2.4.1/sun4x_58/lib/python2.4/shelve.py", line 130, in
__setitem__
    self.dict[key] = f.getvalue()
  File "../spambayes//lib/python2.4/site-
packages/bsddb3/__init__.py", line 218, in __setitem__
bsddb._db.DBAccessError: (13, 'Permission denied --
put: attempt to modify a read-only tree')


----------------------------------------------------------------------

Comment By: David Abrahams (david_abrahams)
Date: 2007-07-25 21:54

Message:
Logged In: YES
user_id=52572
Originator: NO

Did you ever check in this fix?  I'm seeing the same error with the SVN
head, but without train_on_error=True, and more importantly, without the
helpful backtrace :(

  $ echo | sb_filter.py
  opened existing cache with 802 A records and 0 PTR records
  Loading state from /home/dave/spambayes/hammie.fs database
  /home/dave/spambayes/hammie.fs is an existing database, with 728 spam
and 128 ham
  X-Spambayes-Classification: spam; 0.93

  Persisting /home/dave/spambayes/hammie.fs state in database
  Exception bsddb._db.DBAccessError: (13, 'Permission denied -- put:
attempt to modify a read-only tree') in > ignored
  saving 124 items to /home/dave/spambayes/imagecache.pck

My .spambayesrc is attached

----------------------------------------------------------------------

Comment By: Tony Meyer (anadelonbrin)
Date: 2006-04-02 07:05

Message:
Logged In: YES
user_id=552329

Fixed (CVS is down at the moment; I'll check it in once it's
done).

----------------------------------------------------------------------

You can respond by visiting:
https://sourceforge.net/tracker/?func=detail&atid=498103&aid=1387699&group_id=61702

[Succeeded / Failed / Skipped / Total] 2 / 5 / 1 / 8:  80%|████████  | 8/10 [00:39<00:09,  4.98s/it]

--------------------------------------------- Result 8 ---------------------------------------------
[[1 (83%)]] --> [[[FAILED]]]






Grow longer and harder with our all natural supplement. http://www.fiftywait.com/

[Succeeded / Failed / Skipped / Total] 3 / 5 / 1 / 9:  90%|█████████ | 9/10 [00:48<00:05,  5.41s/it]

--------------------------------------------- Result 9 ---------------------------------------------
[[1 (72%)]] --> [[0 (51%)]]

[[This]] [[message]] is [[intended]] for :

*SAVE!  SAVE!  [[SAVE]]!*

[[LOW]] [[COST]] GICENRES
- [[No]] [[Doctor]] [[Fees]] [[Or]] [[Prescriptions]] [[Needed]]
- Lower your monthly [[medication]] expensive
- [[Many]] [[shipping]] options [[available]]

http://fameideal.com


Grove's daily talks, as [[well]] as other perquisites. [[Members]] may also [[invite]] [[guests]] to the Grove although

[[Use]] http://fameideal.com/a.[[php]] for [[removal]]


[[That]] [[signaling]] is [[goals]] for :

*SAVE!  SAVE!  [[SAVINGS]]!*

[[MINUSCULE]] [[FEES]] GICENRES
- [[Any]] [[Pharmaceutical]] [[Dues]] [[U]] [[Regulatory]] [[Owes]]
- Lower your monthly [[medicated]] expensive
- [[Considerable]] [[cargoes]] options [[possible]]

http://fameideal.com


Grove's daily talks, as [[justly]] as other perquisites. [[Delegates]] may also [[urges]] [[diners]] to the Grove although

[[Utilizes]] http://fameideal.com/a.[[pha]] for [[evicting]]

[Succeeded / Failed / Skipped / Total] 4 / 5 / 1 / 10: 100%|██████████| 10/10 [01:54<00:00, 11.49s/it]

--------------------------------------------- Result 10 ---------------------------------------------
[[0 (72%)]] --> [[1 (50%)]]

>[[Thus]] I'm [[concluding]] if it doesn't [[work]] then it [[might]] be a BIOS [[issue]]. Once again:  - The Bios has to reserve address space for PCI devices and [[usually]]     [[reserves]] between 0.5 and 1 GiB.  - To [[make]] the physical RAM that's hidden by that [[reservation]]     [[available]], most BIOSs map this RAM beyond the 4 GiB (2^32)    [[Threshold]]. - To address that memory, you [[need]] a [[kernel]] supporting either    PAE or [[long]] (i.[[e]]. 64 bit) mode. [[If]] the memory isn't [[available]], it's [[rather]] obvious that it is the BIOS that [[failed]] to [[do]] the [[mapping]]. >In PAE the operating [[system]] [[uses]] page tables to [[map]] this 4 GiB >address [[space]] onto the 64 GiB of [[total]] memory, and the map is >[[usually]] different for each [[process]]. You've got something mixed up there. [[Not]] the OS but the processor uses page [[tables]] and it [[does]] that for *all* [[operating]] [[modes]], not only PAE, as virtual [[memory]] management on x86 and x86-64 relies on page tables. [[Philipp]] --  >[[From]] mwbfbfl@santronics.com  Sat Apr 26 15:48:55 2008 Message: 2 Date: Sun, 17 Feb 2008 12:32:40 -0500 From: [[Hector]] Santos  [[Subject]]: Re: [ietf-dkim] Re: ISSUE 1547: SSP-02: MX Record publishing 	mandateto	[[reduce]] DNS [[overhead]] for SSP Discovery and to 	detectfraudulent messages To: Douglas Otis  [[Cc]]: DKIM List  Message-ID: <47B86FB8.8010201@santronics.com> Content-Type: [[text]]/plain; charset Douglas Otis wrote: >> I really don't [[see]] why it [[matters]] from where it sent and how.  [[Do]] you  >> [[have]] a preferred [[type]] of burglar knocking on your [[door]]?  >  > Many different doors could be helped by DKIM.  While there [[might]] [[be]] an  > [[expectation]] that those knocking at the front door will validate their  > [[affiliation]], there may [[be]] [[different]] expectations for those at the back  > door.  The difference might be as [[simply]] as not buying wares from those  > at the back [[door]].  When [[someone]] escorts them to the front door, they  > [[might]] [[be]] [[asked]] to validate their affiliation, although likely unprepared  > to [[do]] [[so]].  While moving everyone to a common doorway may seem ideal,  > this creates a significant problem when the front door carries a greater  > obligation.  Different doors need different policies when there are  > different levels of trust based upon the door used.  At some distant  > point in the future, perhaps all doors will be treated the same, but  > time has not arrived. Doug, That time [[came]] long ago. Remember, this is predominately about anonymous vs non-anonymous  transactions and systems have always treaty anonymous and non-anonymous  transactions differently. An anonymous back door is the last thing we want, although this strongly  appears what the ASP model is promoting. :-) --  Sincerely Hector Santos, CTO http://www.santronics.com http://santronics.blogspot.com ------------------------------ _______________________________________________ NOTE WELL: This list operates according to

>[[Then]] I'm [[finished]] if it doesn't [[operating]] then it [[danger]] be a BIOS [[edition]]. Once again:  - The Bios has to reserve address space for PCI devices and [[always]]     [[reserve]] between 0.5 and 1 GiB.  - To [[creating]] the physical RAM that's hidden by that [[reserved]]     [[accessible]], most BIOSs map this RAM beyond the 4 GiB (2^32)    [[Houghton]]. - To address that memory, you [[suffice]] a [[core]] supporting either    PAE or [[anymore]] (i.[[f]]. 64 bit) mode. [[So]] the memory isn't [[affordable]], it's [[pretty]] obvious that it is the BIOS that [[flawed]] to [[ca]] the [[map]]. >In PAE the operating [[scheme]] [[used]] page tables to [[mapped]] this 4 GiB >address [[spacing]] onto the 64 GiB of [[overall]] memory, and the map is >[[mostly]] different for each [[address]]. You've got something mixed up there. [[Never]] the OS but the processor uses page [[figure]] and it [[wanna]] that for *all* [[functions]] [[styling]], not only PAE, as virtual [[memories]] management on x86 and x86-64 relies on page tables. [[Philip]] --  >[[During]] mwbfbfl@santronics.com  Sat Apr 26 15:48:55 2008 Message: 2 Date: Sun, 17 Feb 2008 12:32:40 -0500 From: [[Vasquez]] Santos  [[Point]]: Re: [ietf-dkim] Re: ISSUE 1547: SSP-02: MX Record publishing 	mandateto	[[diminished]] DNS [[elevated]] for SSP Discovery and to 	detectfraudulent messages To: Douglas Otis  [[Dc]]: DKIM List  Message-ID: <47B86FB8.8010201@santronics.com> Content-Type: [[terminology]]/plain; charset Douglas Otis wrote: >> I really don't [[presume]] why it [[topic]] from where it sent and how.  [[Did]] you  >> [[enjoy]] a preferred [[genera]] of burglar knocking on your [[doors]]?  >  > Many different doors could be helped by DKIM.  While there [[opportunities]] [[fi]] an  > [[forecast]] that those knocking at the front door will validate their  > [[belonged]], there may [[exist]] [[variable]] expectations for those at the back  > door.  The difference might be as [[straightforward]] as not buying wares from those  > at the back [[doorway]].  When [[person]] escorts them to the front door, they  > [[chances]] [[sean]] [[please]] to validate their affiliation, although likely unprepared  > to [[have]] [[whereby]].  While moving everyone to a common doorway may seem ideal,  > this creates a significant problem when the front door carries a greater  > obligation.  Different doors need different policies when there are  > different levels of trust based upon the door used.  At some distant  > point in the future, perhaps all doors will be treated the same, but  > time has not arrived. Doug, That time [[was]] long ago. Remember, this is predominately about anonymous vs non-anonymous  transactions and systems have always treaty anonymous and non-anonymous  transactions differently. An anonymous back door is the last thing we want, although this strongly  appears what the ASP model is promoting. :-) --  Sincerely Hector Santos, CTO http://www.santronics.com http://santronics.blogspot.com ------------------------------ _______________________________________________ NOTE WELL: This list operates according to



+-------------------------------+--------+
| Attack Results                |        |
+-------------------------------+--------+
| Number of successful attacks: | 4      |
| Number of failed attacks:     | 5      |
| Number of skipped attacks:    | 1      |
| Original accuracy:            | 90.0%  |
| Accuracy under attack:        | 50.0%  |
| Attack success rate:          | 44.44% |
| Average perturbed word %:     | 17.79% |
| Average num. words per input: | 167.6  |
| Avg num queries:              | 899.33 |
+-------------------------------+--------+

Generated 10 adversarial samples.
Dataset size: 39 -> 48 (after merging adversarials)
Saved adversarial samples to ./albert_game_model/adversarial_round_1.csv

===== Round 2 / 3 =====

/tmp/ipykernel_1425607/3098119841.py:64: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

textattack: Unknown if model of class <class 'transformers.models.albert.modeling_albert.AlbertForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.

Attack(
  (search_method): GreedyWordSwapWIR(
    (wir_method):  delete
  )
  (goal_function):  UntargetedClassification
  (transformation):  WordSwapEmbedding(
    (max_candidates):  50
    (embedding):  WordEmbedding
  )
  (constraints):
    (0): WordEmbeddingDistance(
        (embedding):  WordEmbedding
        (min_cos_sim):  0.5
        (cased):  False
        (include_unknown_words):  True
        (compare_against_original):  True
      )
    (1): PartOfSpeech(
        (tagger_type):  nltk
        (tagset):  universal
        (allow_verb_noun_swap):  True
        (compare_against_original):  True
      )
    (2): UniversalSentenceEncoder(
        (metric):  angular
        (threshold):  0.840845057
        (window_size):  15
        (skip_text_shorter_than_window):  True
        (compare_against_original):  False
      )
    (3): RepeatModification
    (4): StopwordModification
    (5): InputColumnModification(
        (matching_column_labels):  ['premise', 'hypothesis']
        (columns_to_ignore):  {'premise'}
      )
  (is_black_box):  True
)

[Succeeded / Failed / Skipped / Total] 1 / 0 / 0 / 1:  10%|█         | 1/10 [00:07<01:11,  7.90s/it]

--------------------------------------------- Result 1 ---------------------------------------------
[[1 (92%)]] --> [[0 (50%)]]


[[Dear]] c202f8eb239faf8d4b0a5c6a41cde453

[[Summer]] is a [[great]] [[time]] to take a [[week]] off at [[work]] and [[think]] about your health & [[personal]] [[life]].

And we are [[glad]] to aid you with it.

 From now on till 1st of September you can use our [[specific]] offer.

[[Visit]] our [[site]] for more [[details]].

answerdry.[[com]]

6 [[Aug]] 2008 11:17:23





[[Revered]] c202f8eb239faf8d4b0a5c6a41cde453

[[Sommers]] is a [[formidable]] [[epoch]] to take a [[mois]] off at [[labour]] and [[suppose]] about your health & [[interpersonal]] [[subsistence]].

And we are [[appreciative]] to aid you with it.

 From now on till 1st of September you can use our [[specialised]] offer.

[[Voyages]] our [[places]] for more [[specifies]].

answerdry.[[coms]]

6 [[Jul]] 2008 11:17:23

[Succeeded / Failed / Skipped / Total] 2 / 0 / 0 / 2:  20%|██        | 2/10 [00:10<00:41,  5.18s/it]

--------------------------------------------- Result 2 ---------------------------------------------
[[1 (92%)]] --> [[0 (53%)]]


Why pay more? [[Get]] qualitative [[replica]] watches here

[[Replica]] [[watches]], pens, [[bags]] and more... [[Cheap]] [[luxury]] gifts ...

Ladies and Gents [[watches]] from only 9.99 inc. [[delivery]] ...

http://dryadsnedsjaw.[[com]]/





Why pay more? [[Did]] qualitative [[duplicating]] watches here

[[Retort]] [[timepiece]], pens, [[briefcases]] and more... [[Cheep]] [[swanky]] gifts ...

Ladies and Gents [[clock]] from only 9.99 inc. [[capitulate]] ...

http://dryadsnedsjaw.[[kom]]/

[Succeeded / Failed / Skipped / Total] 2 / 1 / 0 / 3:  30%|███       | 3/10 [00:22<00:52,  7.46s/it]

--------------------------------------------- Result 3 ---------------------------------------------
[[0 (84%)]] --> [[[FAILED]]]

Hi Justin,

I might be biased (x31), but in my experience the wast majority of mac
laptops have a hardware issue. In my experience maybe one out of ten mac
laptop users does _not_ tell about a hardware problem "that happened
only to my machine, otherwise all mac laptops are great" (tm). A
passionate mac user told me once: you buy mac laptops  not because of
but despite the hardware.
And then some stories about the warranty service...
But of course, design and functionality wise they look really tempting ;-)

jm2c,

  Joerg

[Succeeded / Failed / Skipped / Total] 2 / 2 / 0 / 4:  40%|████      | 4/10 [01:44<02:37, 26.17s/it]

--------------------------------------------- Result 4 ---------------------------------------------
[[0 (84%)]] --> [[[FAILED]]]

*************************************************************************
                         Call for papers:

                  Dynamics of Knowledge and Belief

                        Workshop at KI-2007,
   30th Annual German Conference on Artificial Intelligence,
                         September 10, 2007
              http://www.fernuni-hagen.de/wbs/dynamics07

*************************************************************************

Knowledge Representation is one of the major topics in AI. Its concerns
are (logical) formalisms and reasoning, with the intention to explore and
model the basics of intelligent behaviour. In recent years, intelligent
agents in the contexts of open environments and multi agent systems have
become the leading paradigm of the field. Consequently, modern KR methods
have to deal not only with static scenarios, but also with dynamic
modifications in knowledge and belief, due to uncertain or incomplete
information, or to changes in the environment. Moreover, agents are often
expected to learn from past experiences, or to  interact with other
agents, making use of their knowledge and adjusting their beliefs during
argumentation.

The focus of this workshop is on dynamic processes concerning any changes
that an agent's state of knowledge and belief may undergo. Modelling the
continuous cycle of acquiring and applying  knowledge is of particular
interest, so work on relating learning and knowledge representation will
be considered particularly useful. Moreover, the effects of belief changes
on the agent's decisions and behaviour is also within the scope of the
workshop.

We welcome papers on the following and any related topics:
     * Belief revision and belief update
     * Nonmonotonic reasoning
     * Learning and knowledge discovery in data
     * Argumentation theories
     * Decision theory and preferences
     * Action and change

Important Dates:
----------------
     Deadline for Submission:    June 6, 2007
     Notification of Authors:    July 16, 2007
     Final Versions of Papers:   July 30, 2007
     Workshop:                   September 10, 2007

Workshop Organizers and Co-Chairs:
----------------------------------
     Gabriele Kern-Isberner, Universität Dortmund
     Christoph Beierle, FernUniversität in Hagen

Program Committee:
------------------
     Gerd Brewka         Universität Leipzig
     James P. Delgrande  Simon Fraser University
     Jürgen Dix          TU Clausthal-Zellerfeld
     Didier Dubois       Universite Paul Sabatier, Toulouse
     Thomas Eiter        TU Wien
     Esra Erdem          Sabanci University, Istanbul
     Christopher Habel   Universität Hamburg
     Andreas Herzig      Universite Paul Sabatier, Toulouse
     Anthony Hunter      University College London
     Manfred Jaeger      Aalborg University
     Gerhard Lakemeyer   RWTH Aachen
     Jerome Lang         Universite Paul Sabatier, Toulouse
     Bernhard Nebel      Albert-Ludwigs-Universität Freiburg
     Torsten Schaub      Universität Potsdam
     Guillermo Simari    Universidad Nacional del Sur, Bahia Blanca
     Gerhard Weiss       Software Competence Center Hagenberg

Paper Submission and Publication:
---------------------------------
Paper format and submission details are available at
     http://www.fernuni-hagen.de/wbs/dynamics07

**************************************************************************

[Succeeded / Failed / Skipped / Total] 2 / 3 / 0 / 5:  50%|█████     | 5/10 [01:45<01:45, 21.13s/it]

--------------------------------------------- Result 5 ---------------------------------------------
[[1 (83%)]] --> [[[FAILED]]]

Sharon Stone XXX movie! dowload!
http://www.globalnethost.com.br/movz/mov.php

[Succeeded / Failed / Skipped / Total] 3 / 3 / 0 / 6:  60%|██████    | 6/10 [01:55<01:17, 19.30s/it]

--------------------------------------------- Result 6 ---------------------------------------------
[[1 (75%)]] --> [[0 (50%)]]








  Just some [[helpful]] information .
 [[Small]] [[size]] is one of  the  [[common]] [[problems]] for [[many]] [[men]]. However, this [[problem]] could [[be]] [[solved]] in a  safe and inexpensive way. Our Pills [[Will]] [[Expand]], Lengthen and [[Enlarge]] [[Your]] ... !
 We [[understand]]  that most  customers need confidentiality and [[respect]] every [[need]] of our [[clients]]. [[Secure]] [[online]] [[ordering]] [[process]], [[discreet]] [[packing]], security of your private [[information]] are guaranteed.
[[Order]]  VPXL [[today]] ! - [[Click]] Here!













  Just some [[laudable]] information .
 [[Minimized]] [[calibrating]] is one of  the  [[exchanged]] [[questions]] for [[considerable]] [[dawg]]. However, this [[phenomenon]] could [[have]] [[solving]] in a  safe and inexpensive way. Our Pills [[Going]] [[Heightened]], Lengthen and [[Broader]] [[Thy]] ... !
 We [[understood]]  that most  customers need confidentiality and [[adhering]] every [[imperative]] of our [[abusers]]. [[Assuring]] [[cyberspace]] [[dictates]] [[instance]], [[nuanced]] [[wrappers]], security of your private [[endorsements]] are guaranteed.
[[Prescription]]  VPXL [[jour]] ! - [[Clicked]] Here!

[Succeeded / Failed / Skipped / Total] 3 / 4 / 0 / 7:  70%|███████   | 7/10 [03:20<01:25, 28.63s/it]

--------------------------------------------- Result 7 ---------------------------------------------
[[0 (82%)]] --> [[[FAILED]]]

Bugs item #1387699, was opened at 2005-12-21 21:14
Message generated for change (Comment added) made by david_abrahams
You can respond by visiting:
https://sourceforge.net/tracker/?func=detail&atid=498103&aid=1387699&group_id=61702

Please note that this message will contain a full copy of the comment thread,
including the initial issue submission, for this request,
not just the latest update.
Category: hammie
Group: 1.0.4
Status: Closed
Resolution: Fixed
Priority: 5
Private: No
Submitted By: aikiaboy (aikiaboy)
Assigned to: Nobody/Anonymous (nobody)
Summary: train_on_filter=True needs the db to be opened read/write

Initial Comment:
train_on_filter=True needs the db to be opened
read/write for classification

eg.

========================


[globals]
dbm_type=db3hash
verbose=True
[Headers]
include_score=True
[html_ui]
display_adv_find=True
[Storage]
persistent_use_database=dbm
persistent_storage_file=./hammie.db
[Hammie]
train_on_filter=True

=========================

$ sb_filter.py
asdf
fdsa
Loading state
from /u/k/a/kantor/.spambayes/./hammie.db database
/u/k/a/kantor/.spambayes/./hammie.db is an existing
database, with 2273 spam and 711 ham
Traceback (most recent call last):
  File "/u/k/a/kantor/bin/sb_filter.py", line 257, in ?
    main()
  File "/u/k/a/kantor/bin/sb_filter.py", line 248, in
main
    action(msg)
  File "/u/k/a/kantor/bin/sb_filter.py", line 180, in
filter
    return self.h.filter(msg)
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/hammie.py", line 120, in filter
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/hammie.py", line 162, in train
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/classifier.py", line 273, in learn
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/classifier.py", line 384, in
_add_msg
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/storage.py", line 304, in
_wordinfoset
  File "/s/python-
2.4.1/sun4x_58/lib/python2.4/shelve.py", line 130, in
__setitem__
    self.dict[key] = f.getvalue()
  File "../spambayes//lib/python2.4/site-
packages/bsddb3/__init__.py", line 218, in __setitem__
bsddb._db.DBAccessError: (13, 'Permission denied --
put: attempt to modify a read-only tree')


----------------------------------------------------------------------

Comment By: David Abrahams (david_abrahams)
Date: 2007-07-25 21:54

Message:
Logged In: YES
user_id=52572
Originator: NO

Did you ever check in this fix?  I'm seeing the same error with the SVN
head, but without train_on_error=True, and more importantly, without the
helpful backtrace :(

  $ echo | sb_filter.py
  opened existing cache with 802 A records and 0 PTR records
  Loading state from /home/dave/spambayes/hammie.fs database
  /home/dave/spambayes/hammie.fs is an existing database, with 728 spam
and 128 ham
  X-Spambayes-Classification: spam; 0.93

  Persisting /home/dave/spambayes/hammie.fs state in database
  Exception bsddb._db.DBAccessError: (13, 'Permission denied -- put:
attempt to modify a read-only tree') in > ignored
  saving 124 items to /home/dave/spambayes/imagecache.pck

My .spambayesrc is attached

----------------------------------------------------------------------

Comment By: Tony Meyer (anadelonbrin)
Date: 2006-04-02 07:05

Message:
Logged In: YES
user_id=552329

Fixed (CVS is down at the moment; I'll check it in once it's
done).

----------------------------------------------------------------------

You can respond by visiting:
https://sourceforge.net/tracker/?func=detail&atid=498103&aid=1387699&group_id=61702

[Succeeded / Failed / Skipped / Total] 3 / 5 / 0 / 8:  80%|████████  | 8/10 [03:21<00:50, 25.21s/it]

--------------------------------------------- Result 8 ---------------------------------------------
[[1 (92%)]] --> [[[FAILED]]]






Grow longer and harder with our all natural supplement. http://www.fiftywait.com/

[Succeeded / Failed / Skipped / Total] 4 / 5 / 0 / 9:  90%|█████████ | 9/10 [03:23<00:22, 22.64s/it]

--------------------------------------------- Result 9 ---------------------------------------------
[[1 (75%)]] --> [[0 (54%)]]

[[This]] [[message]] is intended for :

*[[SAVE]]!  SAVE!  SAVE!*

[[LOW]] COST GICENRES
- No Doctor Fees Or Prescriptions Needed
- Lower your monthly [[medication]] expensive
- Many shipping options available

[[http]]://fameideal.[[com]]


Grove's daily talks, as well as other perquisites. Members may also invite guests to the [[Grove]] although

Use http://fameideal.com/a.[[php]] for removal


[[That]] [[emails]] is intended for :

*[[ECONOMIC]]!  SAVE!  SAVE!*

[[WEAKER]] COST GICENRES
- No Doctor Fees Or Prescriptions Needed
- Lower your monthly [[pharmacology]] expensive
- Many shipping options available

[[url]]://fameideal.[[kom]]


Grove's daily talks, as well as other perquisites. Members may also invite guests to the [[Oaks]] although

Use http://fameideal.com/a.[[pha]] for removal

[Succeeded / Failed / Skipped / Total] 4 / 6 / 0 / 10: 100%|██████████| 10/10 [04:51<00:00, 29.10s/it]

--------------------------------------------- Result 10 ---------------------------------------------
[[0 (83%)]] --> [[[FAILED]]]

>Thus I'm concluding if it doesn't work then it might be a BIOS issue. Once again:  - The Bios has to reserve address space for PCI devices and usually     reserves between 0.5 and 1 GiB.  - To make the physical RAM that's hidden by that reservation     available, most BIOSs map this RAM beyond the 4 GiB (2^32)    Threshold. - To address that memory, you need a kernel supporting either    PAE or long (i.e. 64 bit) mode. If the memory isn't available, it's rather obvious that it is the BIOS that failed to do the mapping. >In PAE the operating system uses page tables to map this 4 GiB >address space onto the 64 GiB of total memory, and the map is >usually different for each process. You've got something mixed up there. Not the OS but the processor uses page tables and it does that for *all* operating modes, not only PAE, as virtual memory management on x86 and x86-64 relies on page tables. Philipp --  >From mwbfbfl@santronics.com  Sat Apr 26 15:48:55 2008 Message: 2 Date: Sun, 17 Feb 2008 12:32:40 -0500 From: Hector Santos  Subject: Re: [ietf-dkim] Re: ISSUE 1547: SSP-02: MX Record publishing 	mandateto	reduce DNS overhead for SSP Discovery and to 	detectfraudulent messages To: Douglas Otis  Cc: DKIM List  Message-ID: <47B86FB8.8010201@santronics.com> Content-Type: text/plain; charset Douglas Otis wrote: >> I really don't see why it matters from where it sent and how.  Do you  >> have a preferred type of burglar knocking on your door?  >  > Many different doors could be helped by DKIM.  While there might be an  > expectation that those knocking at the front door will validate their  > affiliation, there may be different expectations for those at the back  > door.  The difference might be as simply as not buying wares from those  > at the back door.  When someone escorts them to the front door, they  > might be asked to validate their affiliation, although likely unprepared  > to do so.  While moving everyone to a common doorway may seem ideal,  > this creates a significant problem when the front door carries a greater  > obligation.  Different doors need different policies when there are  > different levels of trust based upon the door used.  At some distant  > point in the future, perhaps all doors will be treated the same, but  > time has not arrived. Doug, That time came long ago. Remember, this is predominately about anonymous vs non-anonymous  transactions and systems have always treaty anonymous and non-anonymous  transactions differently. An anonymous back door is the last thing we want, although this strongly  appears what the ASP model is promoting. :-) --  Sincerely Hector Santos, CTO http://www.santronics.com http://santronics.blogspot.com ------------------------------ _______________________________________________ NOTE WELL: This list operates according to



+-------------------------------+--------+
| Attack Results                |        |
+-------------------------------+--------+
| Number of successful attacks: | 4      |
| Number of failed attacks:     | 6      |
| Number of skipped attacks:    | 0      |
| Original accuracy:            | 100.0% |
| Accuracy under attack:        | 60.0%  |
| Attack success rate:          | 40.0%  |
| Average perturbed word %:     | 29.97% |
| Average num. words per input: | 167.6  |
| Avg num queries:              | 1840.8 |
+-------------------------------+--------+

Generated 10 adversarial samples.
Dataset size: 48 -> 58 (after merging adversarials)
Saved adversarial samples to ./albert_game_model/adversarial_round_2.csv

===== Round 3 / 3 =====

/tmp/ipykernel_1425607/3098119841.py:64: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

textattack: Unknown if model of class <class 'transformers.models.albert.modeling_albert.AlbertForSequenceClassification'> compatible with goal function <class 'textattack.goal_functions.classification.untargeted_classification.UntargetedClassification'>.

Attack(
  (search_method): GreedyWordSwapWIR(
    (wir_method):  delete
  )
  (goal_function):  UntargetedClassification
  (transformation):  WordSwapEmbedding(
    (max_candidates):  50
    (embedding):  WordEmbedding
  )
  (constraints):
    (0): WordEmbeddingDistance(
        (embedding):  WordEmbedding
        (min_cos_sim):  0.5
        (cased):  False
        (include_unknown_words):  True
        (compare_against_original):  True
      )
    (1): PartOfSpeech(
        (tagger_type):  nltk
        (tagset):  universal
        (allow_verb_noun_swap):  True
        (compare_against_original):  True
      )
    (2): UniversalSentenceEncoder(
        (metric):  angular
        (threshold):  0.840845057
        (window_size):  15
        (skip_text_shorter_than_window):  True
        (compare_against_original):  False
      )
    (3): RepeatModification
    (4): StopwordModification
    (5): InputColumnModification(
        (matching_column_labels):  ['premise', 'hypothesis']
        (columns_to_ignore):  {'premise'}
      )
  (is_black_box):  True
)

[Succeeded / Failed / Skipped / Total] 1 / 0 / 0 / 1:  10%|█         | 1/10 [00:09<01:22,  9.16s/it]

--------------------------------------------- Result 1 ---------------------------------------------
[[1 (73%)]] --> [[0 (51%)]]


[[Dear]] c202f8eb239faf8d4b0a5c6a41cde453

[[Summer]] is a [[great]] [[time]] to [[take]] a [[week]] off at [[work]] and [[think]] about your health & personal [[life]].

And we are glad to [[aid]] you with it.

 [[From]] now on till 1st of [[September]] you can [[use]] our [[specific]] [[offer]].

[[Visit]] our [[site]] for more [[details]].

answerdry.com

6 [[Aug]] 2008 11:17:23





[[Cherished]] c202f8eb239faf8d4b0a5c6a41cde453

[[Sommer]] is a [[considerable]] [[duration]] to [[assume]] a [[jours]] off at [[collaborator]] and [[presume]] about your health & personal [[sustenance]].

And we are glad to [[assistance]] you with it.

 [[Du]] now on till 1st of [[Sep]] you can [[employed]] our [[specialised]] [[provision]].

[[Consulted]] our [[locality]] for more [[peculiarities]].

answerdry.com

6 [[August]] 2008 11:17:23

[Succeeded / Failed / Skipped / Total] 2 / 0 / 0 / 2:  20%|██        | 2/10 [00:13<00:53,  6.73s/it]

--------------------------------------------- Result 2 ---------------------------------------------
[[1 (69%)]] --> [[0 (51%)]]


[[Why]] [[pay]] more? [[Get]] qualitative [[replica]] watches here

[[Replica]] [[watches]], [[pens]], [[bags]] and more... [[Cheap]] [[luxury]] [[gifts]] ...

[[Ladies]] and [[Gents]] [[watches]] from only 9.99 [[inc]]. [[delivery]] ...

http://dryadsnedsjaw.com/





[[Thus]] [[wage]] more? [[Perceives]] qualitative [[repetitions]] watches here

[[Reproduced]] [[chronometer]], [[corrals]], [[sachet]] and more... [[Miserly]] [[fascination]] [[grants]] ...

[[Giris]] and [[Fellas]] [[clocks]] from only 9.99 [[lnc]]. [[execution]] ...

http://dryadsnedsjaw.com/

[Succeeded / Failed / Skipped / Total] 2 / 1 / 1 / 4:  40%|████      | 4/10 [00:25<00:38,  6.43s/it]

--------------------------------------------- Result 3 ---------------------------------------------
[[0 (74%)]] --> [[[FAILED]]]

Hi Justin,

I might be biased (x31), but in my experience the wast majority of mac
laptops have a hardware issue. In my experience maybe one out of ten mac
laptop users does _not_ tell about a hardware problem "that happened
only to my machine, otherwise all mac laptops are great" (tm). A
passionate mac user told me once: you buy mac laptops  not because of
but despite the hardware.
And then some stories about the warranty service...
But of course, design and functionality wise they look really tempting ;-)

jm2c,

  Joerg





--------------------------------------------- Result 4 ---------------------------------------------
[[1 (59%)]] --> [[[SKIPPED]]]

*************************************************************************
                         Call for papers:

                  Dynamics of Knowledge and Belief

                        Workshop at KI-2007,
   30th Annual German Conference on Artificial Intelligence,
                         September 10, 2007
              http://www.fernuni-hagen.de/wbs/dynamics07

*************************************************************************

Knowledge Representation is one of the major topics in AI. Its concerns
are (logical) formalisms and reasoning, with the intention to explore and
model the basics of intelligent behaviour. In recent years, intelligent
agents in the contexts of open environments and multi agent systems have
become the leading paradigm of the field. Consequently, modern KR methods
have to deal not only with static scenarios, but also with dynamic
modifications in knowledge and belief, due to uncertain or incomplete
information, or to changes in the environment. Moreover, agents are often
expected to learn from past experiences, or to  interact with other
agents, making use of their knowledge and adjusting their beliefs during
argumentation.

The focus of this workshop is on dynamic processes concerning any changes
that an agent's state of knowledge and belief may undergo. Modelling the
continuous cycle of acquiring and applying  knowledge is of particular
interest, so work on relating learning and knowledge representation will
be considered particularly useful. Moreover, the effects of belief changes
on the agent's decisions and behaviour is also within the scope of the
workshop.

We welcome papers on the following and any related topics:
     * Belief revision and belief update
     * Nonmonotonic reasoning
     * Learning and knowledge discovery in data
     * Argumentation theories
     * Decision theory and preferences
     * Action and change

Important Dates:
----------------
     Deadline for Submission:    June 6, 2007
     Notification of Authors:    July 16, 2007
     Final Versions of Papers:   July 30, 2007
     Workshop:                   September 10, 2007

Workshop Organizers and Co-Chairs:
----------------------------------
     Gabriele Kern-Isberner, Universität Dortmund
     Christoph Beierle, FernUniversität in Hagen

Program Committee:
------------------
     Gerd Brewka         Universität Leipzig
     James P. Delgrande  Simon Fraser University
     Jürgen Dix          TU Clausthal-Zellerfeld
     Didier Dubois       Universite Paul Sabatier, Toulouse
     Thomas Eiter        TU Wien
     Esra Erdem          Sabanci University, Istanbul
     Christopher Habel   Universität Hamburg
     Andreas Herzig      Universite Paul Sabatier, Toulouse
     Anthony Hunter      University College London
     Manfred Jaeger      Aalborg University
     Gerhard Lakemeyer   RWTH Aachen
     Jerome Lang         Universite Paul Sabatier, Toulouse
     Bernhard Nebel      Albert-Ludwigs-Universität Freiburg
     Torsten Schaub      Universität Potsdam
     Guillermo Simari    Universidad Nacional del Sur, Bahia Blanca
     Gerhard Weiss       Software Competence Center Hagenberg

Paper Submission and Publication:
---------------------------------
Paper format and submission details are available at
     http://www.fernuni-hagen.de/wbs/dynamics07

**************************************************************************

[Succeeded / Failed / Skipped / Total] 2 / 2 / 1 / 5:  50%|█████     | 5/10 [00:26<00:26,  5.34s/it]

--------------------------------------------- Result 5 ---------------------------------------------
[[1 (72%)]] --> [[[FAILED]]]

Sharon Stone XXX movie! dowload!
http://www.globalnethost.com.br/movz/mov.php

[Succeeded / Failed / Skipped / Total] 3 / 2 / 1 / 6:  60%|██████    | 6/10 [00:32<00:21,  5.47s/it]

--------------------------------------------- Result 6 ---------------------------------------------
[[1 (74%)]] --> [[0 (51%)]]








  [[Just]] some [[helpful]] [[information]] .
 Small [[size]] is one of  the  common problems for many men. However, this problem could [[be]] solved in a  [[safe]] and [[inexpensive]] way. [[Our]] [[Pills]] [[Will]] [[Expand]], Lengthen and [[Enlarge]] [[Your]] ... !
 [[We]] understand  that most  customers need confidentiality and respect [[every]] need of our clients. [[Secure]] [[online]] [[ordering]] process, discreet [[packing]], [[security]] of your private information are guaranteed.
[[Order]]  VPXL [[today]] ! - Click Here!













  [[Merely]] some [[affirmative]] [[communication]] .
 Small [[extent]] is one of  the  common problems for many men. However, this problem could [[constituted]] solved in a  [[unharmed]] and [[economical]] way. [[Ourselves]] [[Tablet]] [[Willingness]] [[Grew]], Lengthen and [[Augmentation]] [[Tonnes]] ... !
 [[Ourselves]] understand  that most  customers need confidentiality and respect [[any]] need of our clients. [[Protect]] [[otta]] [[behest]] process, discreet [[bottling]], [[seguro]] of your private information are guaranteed.
[[Decree]]  VPXL [[domingos]] ! - Click Here!

[Succeeded / Failed / Skipped / Total] 4 / 2 / 1 / 7:  70%|███████   | 7/10 [01:27<00:37, 12.56s/it]

--------------------------------------------- Result 7 ---------------------------------------------
[[0 (58%)]] --> [[1 (50%)]]

Bugs item #1387699, was opened at 2005-12-21 21:14
Message generated for change ([[Comment]] added) made by david_abrahams
You can respond by visiting:
https://sourceforge.net/tracker/?func=detail&atid=498103&aid=1387699&group_id=61702

Please note that this message will contain a full copy of the comment thread,
including the initial issue submission, for this request,
not just the latest update.
[[Category]]: hammie
[[Group]]: 1.0.4
[[Status]]: Closed
[[Resolution]]: Fixed
[[Priority]]: 5
Private: No
Submitted By: aikiaboy (aikiaboy)
Assigned to: Nobody/Anonymous (nobody)
[[Summary]]: train_on_filter=True needs the db to be opened read/write

Initial Comment:
train_on_filter=True needs the db to be opened
[[read]]/write for classification

[[eg]].

========================


[globals]
dbm_type=db3hash
verbose=True
[Headers]
include_score=True
[html_ui]
display_adv_find=True
[Storage]
persistent_use_database=dbm
persistent_storage_file=./hammie.db
[Hammie]
train_on_filter=True

=========================

$ sb_filter.py
asdf
fdsa
Loading state
from /u/k/a/kantor/.spambayes/./hammie.db database
/u/k/a/kantor/.spambayes/./hammie.[[db]] is an existing
[[database]], with 2273 spam and 711 ham
Traceback (most recent call last):
  File "/u/k/a/kantor/bin/sb_filter.py", line 257, in ?
    [[main]]()
  File "/u/k/a/kantor/bin/sb_filter.py", line 248, in
main
    [[action]](msg)
  File "/u/k/a/kantor/bin/sb_filter.py", line 180, in
filter
    return self.h.filter(msg)
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/hammie.py", line 120, in filter
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/hammie.py", line 162, in train
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/classifier.py", line 273, in learn
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/classifier.py", line 384, in
_add_msg
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/storage.py", line 304, in
_wordinfoset
  File "/s/python-
2.4.1/sun4x_58/lib/python2.4/[[shelve]].py", [[line]] 130, in
__setitem__
    self.dict[key] = f.getvalue()
  File "../spambayes//lib/python2.4/site-
packages/bsddb3/__init__.py", line 218, in __setitem__
bsddb._db.DBAccessError: (13, 'Permission denied --
put: attempt to modify a read-only tree')


----------------------------------------------------------------------

Comment By: David Abrahams (david_abrahams)
Date: 2007-07-25 21:54

Message:
Logged In: YES
user_id=52572
Originator: NO

Did you ever check in this fix?  I'm seeing the same error with the SVN
head, but without train_on_error=True, and more importantly, without the
helpful backtrace :(

  $ echo | sb_filter.py
  opened existing cache with 802 A records and 0 PTR records
  Loading state from /home/dave/spambayes/hammie.fs database
  /home/dave/spambayes/hammie.fs is an existing database, with 728 spam
and 128 ham
  X-Spambayes-Classification: spam; 0.93

  Persisting /home/dave/spambayes/hammie.fs state in database
  Exception bsddb._db.DBAccessError: (13, 'Permission denied -- put:
attempt to modify a read-only tree') in > ignored
  saving 124 items to /home/dave/spambayes/imagecache.pck

My .spambayesrc is attached

----------------------------------------------------------------------

Comment By: Tony Meyer (anadelonbrin)
Date: 2006-04-02 07:05

Message:
Logged In: YES
user_id=552329

Fixed (CVS is down at the moment; I'll check it in once it's
done).

----------------------------------------------------------------------

You can respond by visiting:
https://sourceforge.net/tracker/?func=detail&atid=498103&aid=1387699&group_id=61702




Bugs item #1387699, was opened at 2005-12-21 21:14
Message generated for change ([[Feedback]] added) made by david_abrahams
You can respond by visiting:
https://sourceforge.net/tracker/?func=detail&atid=498103&aid=1387699&group_id=61702

Please note that this message will contain a full copy of the comment thread,
including the initial issue submission, for this request,
not just the latest update.
[[Categorize]]: hammie
[[Consortium]]: 1.0.4
[[Proviso]]: Closed
[[Determination]]: Fixed
[[Focus]]: 5
Private: No
Submitted By: aikiaboy (aikiaboy)
Assigned to: Nobody/Anonymous (nobody)
[[Synthesis]]: train_on_filter=True needs the db to be opened read/write

Initial Comment:
train_on_filter=True needs the db to be opened
[[leah]]/write for classification

[[ec]].

========================


[globals]
dbm_type=db3hash
verbose=True
[Headers]
include_score=True
[html_ui]
display_adv_find=True
[Storage]
persistent_use_database=dbm
persistent_storage_file=./hammie.db
[Hammie]
train_on_filter=True

=========================

$ sb_filter.py
asdf
fdsa
Loading state
from /u/k/a/kantor/.spambayes/./hammie.db database
/u/k/a/kantor/.spambayes/./hammie.[[bp]] is an existing
[[data]], with 2273 spam and 711 ham
Traceback (most recent call last):
  File "/u/k/a/kantor/bin/sb_filter.py", line 257, in ?
    [[nucleus]]()
  File "/u/k/a/kantor/bin/sb_filter.py", line 248, in
main
    [[proceedings]](msg)
  File "/u/k/a/kantor/bin/sb_filter.py", line 180, in
filter
    return self.h.filter(msg)
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/hammie.py", line 120, in filter
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/hammie.py", line 162, in train
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/classifier.py", line 273, in learn
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/classifier.py", line 384, in
_add_msg
  File "/u/k/a/kantor/bin/spambayes/lib/python2.4/site-
packages/spambayes/storage.py", line 304, in
_wordinfoset
  File "/s/python-
2.4.1/sun4x_58/lib/python2.4/[[bookshelves]].py", [[accordance]] 130, in
__setitem__
    self.dict[key] = f.getvalue()
  File "../spambayes//lib/python2.4/site-
packages/bsddb3/__init__.py", line 218, in __setitem__
bsddb._db.DBAccessError: (13, 'Permission denied --
put: attempt to modify a read-only tree')


----------------------------------------------------------------------

Comment By: David Abrahams (david_abrahams)
Date: 2007-07-25 21:54

Message:
Logged In: YES
user_id=52572
Originator: NO

Did you ever check in this fix?  I'm seeing the same error with the SVN
head, but without train_on_error=True, and more importantly, without the
helpful backtrace :(

  $ echo | sb_filter.py
  opened existing cache with 802 A records and 0 PTR records
  Loading state from /home/dave/spambayes/hammie.fs database
  /home/dave/spambayes/hammie.fs is an existing database, with 728 spam
and 128 ham
  X-Spambayes-Classification: spam; 0.93

  Persisting /home/dave/spambayes/hammie.fs state in database
  Exception bsddb._db.DBAccessError: (13, 'Permission denied -- put:
attempt to modify a read-only tree') in > ignored
  saving 124 items to /home/dave/spambayes/imagecache.pck

My .spambayesrc is attached

----------------------------------------------------------------------

Comment By: Tony Meyer (anadelonbrin)
Date: 2006-04-02 07:05

Message:
Logged In: YES
user_id=552329

Fixed (CVS is down at the moment; I'll check it in once it's
done).

----------------------------------------------------------------------

You can respond by visiting:
https://sourceforge.net/tracker/?func=detail&atid=498103&aid=1387699&group_id=61702

[Succeeded / Failed / Skipped / Total] 4 / 3 / 1 / 8:  80%|████████  | 8/10 [01:29<00:22, 11.14s/it]

--------------------------------------------- Result 8 ---------------------------------------------
[[1 (75%)]] --> [[[FAILED]]]






Grow longer and harder with our all natural supplement. http://www.fiftywait.com/

[Succeeded / Failed / Skipped / Total] 5 / 3 / 1 / 9:  90%|█████████ | 9/10 [01:34<00:10, 10.51s/it]

--------------------------------------------- Result 9 ---------------------------------------------
[[1 (65%)]] --> [[0 (50%)]]

[[This]] message is intended for :

*[[SAVE]]!  [[SAVE]]!  [[SAVE]]!*

[[LOW]] [[COST]] GICENRES
- [[No]] Doctor Fees Or [[Prescriptions]] Needed
- [[Lower]] your [[monthly]] medication [[expensive]]
- Many [[shipping]] [[options]] available

http://fameideal.com


Grove's daily talks, as [[well]] as other perquisites. [[Members]] may also invite guests to the [[Grove]] although

[[Use]] http://fameideal.com/a.php for [[removal]]


[[That]] message is intended for :

*[[ECONOMIES]]!  [[ASCETICISM]]!  [[CONSERVATION]]!*

[[MARGINALLY]] [[COSTING]] GICENRES
- [[Absence]] Doctor Fees Or [[Statutes]] Needed
- [[Diminish]] your [[weekly]] medication [[costly]]
- Many [[maritime]] [[possibility]] available

http://fameideal.com


Grove's daily talks, as [[satisfactorily]] as other perquisites. [[Delegated]] may also invite guests to the [[Orchards]] although

[[Utilise]] http://fameideal.com/a.php for [[abolishing]]

[Succeeded / Failed / Skipped / Total] 5 / 4 / 1 / 10: 100%|██████████| 10/10 [03:02<00:00, 18.21s/it]

--------------------------------------------- Result 10 ---------------------------------------------
[[0 (80%)]] --> [[[FAILED]]]

>Thus I'm concluding if it doesn't work then it might be a BIOS issue. Once again:  - The Bios has to reserve address space for PCI devices and usually     reserves between 0.5 and 1 GiB.  - To make the physical RAM that's hidden by that reservation     available, most BIOSs map this RAM beyond the 4 GiB (2^32)    Threshold. - To address that memory, you need a kernel supporting either    PAE or long (i.e. 64 bit) mode. If the memory isn't available, it's rather obvious that it is the BIOS that failed to do the mapping. >In PAE the operating system uses page tables to map this 4 GiB >address space onto the 64 GiB of total memory, and the map is >usually different for each process. You've got something mixed up there. Not the OS but the processor uses page tables and it does that for *all* operating modes, not only PAE, as virtual memory management on x86 and x86-64 relies on page tables. Philipp --  >From mwbfbfl@santronics.com  Sat Apr 26 15:48:55 2008 Message: 2 Date: Sun, 17 Feb 2008 12:32:40 -0500 From: Hector Santos  Subject: Re: [ietf-dkim] Re: ISSUE 1547: SSP-02: MX Record publishing 	mandateto	reduce DNS overhead for SSP Discovery and to 	detectfraudulent messages To: Douglas Otis  Cc: DKIM List  Message-ID: <47B86FB8.8010201@santronics.com> Content-Type: text/plain; charset Douglas Otis wrote: >> I really don't see why it matters from where it sent and how.  Do you  >> have a preferred type of burglar knocking on your door?  >  > Many different doors could be helped by DKIM.  While there might be an  > expectation that those knocking at the front door will validate their  > affiliation, there may be different expectations for those at the back  > door.  The difference might be as simply as not buying wares from those  > at the back door.  When someone escorts them to the front door, they  > might be asked to validate their affiliation, although likely unprepared  > to do so.  While moving everyone to a common doorway may seem ideal,  > this creates a significant problem when the front door carries a greater  > obligation.  Different doors need different policies when there are  > different levels of trust based upon the door used.  At some distant  > point in the future, perhaps all doors will be treated the same, but  > time has not arrived. Doug, That time came long ago. Remember, this is predominately about anonymous vs non-anonymous  transactions and systems have always treaty anonymous and non-anonymous  transactions differently. An anonymous back door is the last thing we want, although this strongly  appears what the ASP model is promoting. :-) --  Sincerely Hector Santos, CTO http://www.santronics.com http://santronics.blogspot.com ------------------------------ _______________________________________________ NOTE WELL: This list operates according to



+-------------------------------+---------+
| Attack Results                |         |
+-------------------------------+---------+
| Number of successful attacks: | 5       |
| Number of failed attacks:     | 4       |
| Number of skipped attacks:    | 1       |
| Original accuracy:            | 90.0%   |
| Accuracy under attack:        | 40.0%   |
| Attack success rate:          | 55.56%  |
| Average perturbed word %:     | 31.14%  |
| Average num. words per input: | 167.6   |
| Avg num queries:              | 1296.33 |
+-------------------------------+---------+

Generated 10 adversarial samples.
Dataset size: 58 -> 67 (after merging adversarials)
Saved adversarial samples to ./albert_game_model/adversarial_round_3.csv

: